services:
  - type: web
    name: llm-litreview-backend
    runtime: python
    repo: https://github.com/aswathylofyraj/SR_MOA.git
    branch: main
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
